namespace MemoRecipeIA.Application.Dtos;

/// <summary>
/// Result of an LLM completion call.
/// Includes the generated text and token usage for audit trail + cost tracking (US-A2-04c / US-A2-05).
/// PromptTokens = input tokens sent to the model.
/// CompletionTokens = output tokens generated by the model.
/// Both = 0 if the provider response did not include a usage section.
/// </summary>
public record LlmCompletionResult(
    string Text,
    int PromptTokens,
    int CompletionTokens);